import type { RoomAnalysisMockText } from '../src/types/roomAnalysis.js'

export const mockRoomAnalysisContent: Record<'es' | 'en', RoomAnalysisMockText> = {
  es: {
    labels: {
      futureCatalog: 'Catalogo futuro',
      alternativeFutureStore: 'Tienda futura alternativa',
      dimensionsNote: 'Medidas aproximadas para validar encaje en el futuro.',
      placementAdvice: 'Mantener al menos 70 cm de paso libre en la circulacion principal.',
    },
    errors: {
      invalidImage: 'Sube una imagen valida.',
      imageTooLarge: 'La imagen es demasiado grande. Prueba con una foto menor de 8 MB.',
      readFailure: 'No pudimos leer la imagen de la habitacion.',
    },
    alternatives: {
      cheaperSuffix: 'opcion economica',
      premiumSuffix: 'opcion premium',
      smallSpaceSuffix: 'opcion compacta',
      otherStoreSuffix: 'opcion en otra tienda',
      cheaperReason: 'Alternativa mas economica preparada para comparar precio.',
      premiumReason: 'Alternativa premium preparada para comparar mejora visual.',
      smallSpaceReason: 'Alternativa compacta si falta paso libre.',
      otherStoreReason: 'Alternativa futura en otra tienda cuando haya catalogo conectado.',
    },
    products: [
      {
        id: 'storage-low-001',
        name: 'Mueble bajo de almacenaje',
        category: 'Almacenamiento',
        reason: 'Aprovecha una pared vacia y reduce ruido visual sin consumir demasiado presupuesto.',
        color: 'roble claro',
        imageType: 'storage',
        status: 'smartFit',
        priority: 'essential',
        widthCm: 120,
        depthCm: 40,
        heightCm: 72,
        budgetRatio: 0.18,
        score: 91,
      },
      {
        id: 'lamp-warm-001',
        name: 'Lampara ambiental calida',
        category: 'Iluminacion',
        reason: 'Anade una segunda capa de luz para que la habitacion se sienta mas terminada.',
        color: 'negro mate',
        imageType: 'lamp',
        status: 'budgetFriendly',
        priority: 'recommended',
        widthCm: 32,
        depthCm: 32,
        heightCm: 150,
        budgetRatio: 0.08,
        score: 88,
      },
      {
        id: 'desk-compact-001',
        name: 'Escritorio compacto o consola',
        category: 'Escritorio',
        reason: 'Crea una zona util sin bloquear el paso ni romper la linea visual del espacio.',
        color: 'blanco roto',
        imageType: 'desk',
        status: 'styleMatch',
        priority: 'optional',
        widthCm: 100,
        depthCm: 48,
        heightCm: 75,
        budgetRatio: 0.16,
        score: 86,
      },
    ],
    packs: {
      basic: {
        id: 'pack-basic',
        title: 'Pack basico funcional',
        summary: 'Resuelve luz y orden con minima inversion.',
        pros: ['Menor coste', 'Facil de comprar'],
        cons: ['Transformacion visual limitada'],
      },
      recommended: {
        id: 'pack-recommended',
        title: 'Pack habitacion lista',
        summary: 'Equilibra diseno, utilidad y presupuesto.',
        pros: ['Mejor equilibrio', 'Compra completa'],
        cons: ['Requiere validar medidas reales'],
      },
      premium: {
        id: 'pack-premium',
        title: 'Pack premium elevado',
        summary: 'Sube materiales, presencia visual y durabilidad.',
        pros: ['Mayor impacto visual', 'Mejores acabados'],
        cons: ['Puede superar el presupuesto objetivo'],
      },
    },
    room: {
      fallbackRoom: 'Dormitorio',
      fallbackStyle: 'moderno',
      fallbackSize: 'Mediano',
      lighting: 'Luz natural suave',
      styleCues: 'Base {{style}} con lineas limpias',
      colors: ['beige suave', 'carbon', 'verde apagado'],
      spaceProblems: ['La iluminacion necesita una segunda capa', 'Faltan medidas exactas para validar encaje'],
      missingFurniture: ['almacenamiento', 'una lampara'],
      clutterLevel: 'Moderado',
      budgetFitTight: 'Ajustado pero practico',
      budgetFitBalanced: 'Bien equilibrado',
      budgetFitPremium: 'Listo para mejoras premium',
      summary: 'Analisis de habitacion listo: el espacio parece un {{room}} con luz suave y una base {{style}}. La recomendacion prioriza muebles que se puedan comprar como pack, validar con medidas y adaptar al presupuesto.',
      nextAction: 'Confirma medidas y sube otro angulo para afinar encaje, carrito y plan visual.',
      layoutSummary: 'Distribucion sugerida con pared aprovechable y paso a proteger.',
      naturalLight: 'Luz natural suave con posible variacion de color.',
      existingFurniture: 'mueble existente no validado',
      measurementNotes: 'Medidas pendientes de confirmar por usuario.',
    },
    zones: {
      mainWallLabel: 'Pared principal',
      mainWallPurpose: 'Almacenaje y foco visual',
      mainWallAdvice: 'Usar piezas bajas para no saturar.',
      circulationLabel: 'Paso principal',
      circulationPurpose: 'Mantener paso libre',
      circulationAdvice: 'No colocar muebles voluminosos.',
    },
    obstacles: {
      windowLabel: 'Ventana o fuente de luz probable',
    },
    layoutSuggestion: {
      title: 'Proteger paso principal',
      description: 'Mantener al menos 70 cm libres antes de recomendar piezas grandes.',
    },
    visualMockupPlan: {
      storageInstruction: 'Colocar centrado en la pared libre.',
      lampInstruction: 'Colocar junto al mueble para crear luz lateral.',
      storageLabel: 'Zona de almacenaje',
      clearanceLabel: 'Paso libre 70 cm',
      beforeAfterPrompt: 'Plan visual futuro: mantener la foto original, anadir muebles recomendados y senalar zonas de paso.',
    },
    commercialSummary: {
      packTitle: 'Tu habitacion lista en un pack comprable',
      readyRoomSummary: 'Un pack equilibrado para ordenar, iluminar y dar funcion al espacio sin superar el presupuesto.',
      recommendedCta: 'Ver pack recomendado',
    },
    warnings: {
      measurements: 'Faltan medidas exactas: valida ancho, fondo y zonas de paso antes de comprar.',
      measurementsAction: 'Anade medidas o sube otro angulo.',
      lightColor: 'La luz de la foto puede alterar el color real de los muebles.',
    },
    analysisSteps: {
      room: 'Habitacion detectada',
      layout: 'Zonas y obstaculos',
      pack: 'Pack comprable',
    },
    nextActions: {
      saveVersion: 'Guardar esta version de habitacion',
      comparePacks: 'Comparar pack basico, recomendado y premium',
      regenerateBudget: 'Regenerar con otro presupuesto',
    },
    regeneration: {
      lowerBudget: 'Bajar presupuesto',
      upgradePremium: 'Subir a premium',
    },
  },
  en: {
    labels: {
      futureCatalog: 'Future catalog',
      alternativeFutureStore: 'Alternative future store',
      dimensionsNote: 'Approximate dimensions for future fit validation.',
      placementAdvice: 'Keep at least 70 cm of circulation clearance around the main path.',
    },
    errors: {
      invalidImage: 'Upload a valid image.',
      imageTooLarge: 'The image is too large. Try a photo under 8 MB.',
      readFailure: 'Could not read the room image.',
    },
    alternatives: {
      cheaperSuffix: 'budget option',
      premiumSuffix: 'premium option',
      smallSpaceSuffix: 'compact option',
      otherStoreSuffix: 'other store option',
      cheaperReason: 'Prepared cheaper alternative for price comparison.',
      premiumReason: 'Prepared premium alternative for visual upgrade comparison.',
      smallSpaceReason: 'Prepared compact alternative if clearance is limited.',
      otherStoreReason: 'Prepared alternate-store option for future catalog routing.',
    },
    products: [
      {
        id: 'storage-low-001',
        name: 'Low storage unit',
        category: 'Storage',
        reason: 'Uses an empty wall and reduces visual noise without consuming too much budget.',
        color: 'light oak',
        imageType: 'storage',
        status: 'smartFit',
        priority: 'essential',
        widthCm: 120,
        depthCm: 40,
        heightCm: 72,
        budgetRatio: 0.18,
        score: 91,
      },
      {
        id: 'lamp-warm-001',
        name: 'Warm ambient lamp',
        category: 'Lighting',
        reason: 'Adds a second lighting layer so the room feels more finished.',
        color: 'matte black',
        imageType: 'lamp',
        status: 'budgetFriendly',
        priority: 'recommended',
        widthCm: 32,
        depthCm: 32,
        heightCm: 150,
        budgetRatio: 0.08,
        score: 88,
      },
      {
        id: 'desk-compact-001',
        name: 'Compact desk or console',
        category: 'Desk',
        reason: 'Creates a useful zone without blocking circulation or breaking the visual line.',
        color: 'warm white',
        imageType: 'desk',
        status: 'styleMatch',
        priority: 'optional',
        widthCm: 100,
        depthCm: 48,
        heightCm: 75,
        budgetRatio: 0.16,
        score: 86,
      },
    ],
    packs: {
      basic: {
        id: 'pack-basic',
        title: 'Functional basic pack',
        summary: 'Solves light and storage with minimal spend.',
        pros: ['Lowest cost', 'Easy to buy'],
        cons: ['Limited visual transformation'],
      },
      recommended: {
        id: 'pack-recommended',
        title: 'Ready-room pack',
        summary: 'Balances design, utility, and budget.',
        pros: ['Best balance', 'Complete purchase'],
        cons: ['Requires real measurement validation'],
      },
      premium: {
        id: 'pack-premium',
        title: 'Elevated premium pack',
        summary: 'Upgrades materials, visual presence, and durability.',
        pros: ['Higher visual impact', 'Better finishes'],
        cons: ['May exceed target budget'],
      },
    },
    room: {
      fallbackRoom: 'Bedroom',
      fallbackStyle: 'modern',
      fallbackSize: 'Medium',
      lighting: 'Soft natural light',
      styleCues: '{{style}} base with clean lines',
      colors: ['soft beige', 'charcoal', 'muted green'],
      spaceProblems: ['Lighting needs a second layer', 'Exact measurements are missing for fit validation'],
      missingFurniture: ['storage', 'a lamp'],
      clutterLevel: 'Moderate',
      budgetFitTight: 'Tight but practical',
      budgetFitBalanced: 'Well-balanced',
      budgetFitPremium: 'Premium upgrade ready',
      summary: 'Room analysis ready: the space reads as a {{room}} with soft light and a {{style}} base. The recommendation prioritizes furniture that can become a shoppable pack, be validated by measurements, and adapt to budget.',
      nextAction: 'Confirm measurements and upload another angle to refine fit, cart, and visual planning.',
      layoutSummary: 'Suggested layout with a usable wall and circulation to protect.',
      naturalLight: 'Soft natural light with possible color shift.',
      existingFurniture: 'unvalidated existing furniture',
      measurementNotes: 'Measurements pending user confirmation.',
    },
    zones: {
      mainWallLabel: 'Main wall',
      mainWallPurpose: 'Storage and visual anchor',
      mainWallAdvice: 'Use low pieces to avoid visual weight.',
      circulationLabel: 'Main circulation',
      circulationPurpose: 'Keep movement clear',
      circulationAdvice: 'Avoid bulky furniture.',
    },
    obstacles: {
      windowLabel: 'Likely window or light source',
    },
    layoutSuggestion: {
      title: 'Protect main circulation',
      description: 'Keep at least 70 cm clear before recommending large pieces.',
    },
    visualMockupPlan: {
      storageInstruction: 'Place centered on the open wall.',
      lampInstruction: 'Place beside storage for side lighting.',
      storageLabel: 'Storage zone',
      clearanceLabel: '70 cm clearance',
      beforeAfterPrompt: 'Future visual plan: keep the original photo, add recommended furniture, and label circulation zones.',
    },
    commercialSummary: {
      packTitle: 'Your room ready in one shoppable pack',
      readyRoomSummary: 'A balanced pack to organize, light, and add function without exceeding the budget.',
      recommendedCta: 'View recommended pack',
    },
    warnings: {
      measurements: 'Exact measurements are missing: validate width, depth, and clearance before buying.',
      measurementsAction: 'Add measurements or upload another angle.',
      lightColor: 'Photo lighting can alter the real color of furniture.',
    },
    analysisSteps: {
      room: 'Room detected',
      layout: 'Zones and obstacles',
      pack: 'Shoppable pack',
    },
    nextActions: {
      saveVersion: 'Save this room version',
      comparePacks: 'Compare basic, recommended and premium packs',
      regenerateBudget: 'Regenerate with another budget',
    },
    regeneration: {
      lowerBudget: 'Lower budget',
      upgradePremium: 'Upgrade to premium',
    },
  },
}
